# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

resolver: lts-7.0
packages:
    - 'api-gateway'
    - 'csim-sim'

# Dependency from Hackage. NATS client for Haskell.
extra-deps: [hats-0.1.0.0]

# Override default flag values for local packages and extra-deps
flags: {}

extra-package-dbs: []
